# Generated by Django 4.2 on 2023-05-22 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Siete', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='fecha_finalizacion',
            new_name='fecha_vencimiento',
        ),
    ]
