# Generated by Django 4.2 on 2023-05-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Siete', '0002_rename_fecha_finalizacion_tarea_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
