# Generated by Django 4.2 on 2023-05-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Siete', '0003_tarea_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
